# This workflow will do a clean installation of node dependencies, cache/restore them, run tests, and build & deploy the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - name: Run tests
        run: pnpm test

  build-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - name: Build
        run: pnpm run build # The build command of your project
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
